### ISSUE TITLE
Tensor mode indexing

### ISSUE THREAD

**Issue by JiyuFang-git** [IlyaKisil/dpm-coursework#2]
![image](https://user-images.githubusercontent.com/24462863/55356563-f0b08680-54c2-11e9-8104-a9cea07f7efa.png)
For the above assignment in tensor unfolding, do you mean A.unfold(mode=1) or mode-2 unfolding ( A.unfold(mode=2))?

**Comment by IlyaKisil** [comment]
Hi @IceyFong, thanks for pointing out this ambiguity. Use `A.unfold(mode=1)`
