### ISSUE TITLE
Repeated work in assngments

### ISSUE THREAD

**Issue by JiyuFang-git** [IlyaKisil/dpm-coursework#4]
For Q1&Q2 in assignment2 of module 3:

1.Use multi-linear rank equal to (50, 50, 2) in order to obtain Tucker representations of images of the car and apple. Analyse results by visually inspecting their reconstructions.

2.Use multi-linear rank equal to (50, 50, 2) in order to obtain Tucker representations of images of the apple taken from the top and from the side. Analyse results by visually inspecting their reconstructions.

I think these 2 questions overlap?

Thank you

**Comment by IlyaKisil** [comment]
Yes, they were intended to overlap. The difference should become clearer when you attempt to complete them and should be explained in the analysis.
